name: TShop
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  #Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.11
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  #State management
  get: ^4.6.5
  get_storage: ^2.1.1
  #Product Specific
  
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/on_boarding_images/
    - assets/images/user/
    - assets/logos/
    - assets/images/banners/
    - assets/images/products/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        # - asset: assets/fonts/Poppins-BoldItalic.ttf
        # - asset: assets/fonts/Poppins-LightItalic.ttf
        # - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
